import unreal,json
from pathlib import Path
bp=unreal.load_asset('/Game/BP/Widget/WBP_LobbyStageSelect');tree=unreal.find_object(bp,'WidgetTree')
def w(n):return unreal.find_object(tree,n)
def rect(n,x,y,width,height,z=None):
    s=w(n).get_editor_property('slot');s.set_position(unreal.Vector2D(x,y));s.set_size(unreal.Vector2D(width,height))
    if z is not None:s.set_z_order(z)
def text(n,value=None,size=None,color=None,center=False):
    t=w(n)
    if value is not None:t.set_text(value)
    if size:
        f=t.get_editor_property('font');f.set_editor_property('size',size);t.set_font(f)
    if color:t.set_color_and_opacity(unreal.SlateColor(specified_color=unreal.LinearColor(*color)))
    if center:t.set_editor_property('justification',unreal.TextJustify.CENTER)
def hide(n):w(n).set_visibility(unreal.SlateVisibility.COLLAPSED)
back=w('StageSelectBackdrop');back.set_brush_from_material(unreal.load_asset('/Game/UI/StagePreview/M_UI_StageBackdrop'));back.set_visibility(unreal.SlateVisibility.HIT_TEST_INVISIBLE)
s=back.get_editor_property('slot');s.set_anchors(unreal.Anchors(minimum=unreal.Vector2D(0,0),maximum=unreal.Vector2D(1,1)));s.set_offsets(unreal.Margin(0,0,0,0));s.set_z_order(-10)
rect('StagePanel',0,0,1800,1000)
rect('ScreenCaption',40,22,400,34);text('ScreenCaption','STAGE SELECT  /  RESEARCH LINK',18,(.1,.7,.9,1))
rect('Text_StageNumber',550,35,700,64);text('Text_StageNumber',size=44,color=(1,.75,.12,1),center=True)
rect('StageName',480,106,840,66);text('StageName',size=36,color=(.8,.95,1,1),center=True)
rect('Button_PreviousFrame',405,52,105,72);rect('Button_NextFrame',1290,52,105,72)
text('Button_PreviousLabel','‹',38);text('Button_NextLabel','›',38)
for i,n in enumerate(['Previous','Current','Next']):
    pre='Carousel'+n
    rect(pre,80+i*470,183,700,510)
    w(pre).set_render_transform_pivot(unreal.Vector2D(.5,.5))
    rect(pre+'Frame',10,-5,680,510,-1);w(pre+'Frame').set_brush_from_material(unreal.load_asset('/Game/UI/StagePreview/M_UI_DioramaRing'))
    rect(pre+'Image',0,0,700,525,0)
    rect(pre+'Label',30,457,640,38,3);text(pre+'Label',size=23,center=True)
    rect(pre+'Badge',190,398,320,44,4);text(pre+'Badge',size=29,color=(1,.8,.15,1),center=True)
    rect(pre+'Empty',110,225,480,50,2);text(pre+'Empty',size=24,center=True)
    rect(pre+'Lock',305,215,90,95,5)
    if n!='Current':w(pre).set_visibility(unreal.SlateVisibility.COLLAPSED)
rect('HoloPanel',38,718,1325,255,-1)
rect('PreviewCaption',70,735,1160,35);text('PreviewCaption','MISSION DATA  / /',22,(.15,.8,1,1))
rect('ObjectiveCaption',75,786,330,38);text('ObjectiveCaption','目標捕獲数',24)
rect('TargetCount',425,783,180,43);text('TargetCount',size=30,color=(1,.8,.12,1))
rect('Text_StageProgress',75,830,660,83);text('Text_StageProgress',size=25)
rect('Text_StageStatus',75,922,650,38);text('Text_StageStatus',size=24,color=(1,.8,.12,1))
rect('StageDescription',765,789,540,135);text('StageDescription',size=23);w('StageDescription').set_editor_property('auto_wrap_text',True)
rect('StartStageButtonFrame',1400,745,345,83);text('StartLabel','決定 / CONFIRM',26)
rect('CancelActionFrame',1400,845,345,83);text('CancelLabel','戻る / BACK',26)
rect('InputGuide',1400,938,360,48);text('InputGuide','決定：Enter / パッド下ボタン\n戻る：Esc / パッド右ボタン',15)
for n in ['CatalogPanel','StageThumbnail','TargetUnit','EncyclopediaFrame']:hide(n)
cdo=unreal.get_default_object(bp.generated_class());cdo.set_editor_property('preview_material',unreal.load_asset('/Game/UI/StagePreview/M_UI_Diorama'))
unreal.BlueprintEditorLibrary.compile_blueprint(bp)
if not unreal.get_editor_subsystem(unreal.EditorAssetSubsystem).save_loaded_asset(bp):raise RuntimeError('Save failed')
Path(__file__).with_suffix('.json').write_text(json.dumps({'saved':True,'carousel':cdo.get_editor_property('use_carousel')},indent=2))
